# Generated by Django 6.1 on 2026-08-07 11:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmark',
            old_name='mar',
            new_name='mark',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='derection',
        ),
        migrations.AddField(
            model_name='group',
            name='created_ad',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='direction',
            field=models.CharField(choices=[('backend', 'Back-End'), ('fronted', 'Front-End'), ('smm', 'SMM')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='students/'),
        ),
    ]
