# Generated by Django 6.1 on 2026-08-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_rename_mar_studentmark_mark_remove_teacher_derection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='created_ad',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='created_ad',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='direction',
            field=models.CharField(choices=[('backend', 'Back-End'), ('frontend', 'Front-End'), ('smm', 'SMM')], max_length=20),
        ),
    ]
